spring:
  config:
    activate:
      on-profile: proc
  application:
    name: kss
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:51443}
      database:
        pubsub: 0
        crud: 1
local:
  storage:
    filepath: "/labels"