spring:
  config:
    activate:
      on-profile: dev
  application:
    name: kss
  data:
    redis:
      host: localhost
      port: 51443
      database:
        pubsub: 0
        crud: 1
local:
  storage:
    filepath: "/labels"